# Generated by Django 5.2.14 on 2026-05-22 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_comment',
            new_name='post_comments',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_comment',
            new_name='user_comments',
        ),
    ]
